version: "3"
services:
 app:
  restart: always
  build: .
  command: "python3 manage.py runserver 0.0.0.0:18000 --noreload"
  volumes:
   - .:/code
   - /path/to/mdict/library:/library
  ports:
   - "18000:8090"
