from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'mdict'
urlpatterns = [
    path('', views.mdict_index),
    path('sug/', views.search_suggestion),
    url(r'^(\d+)/(.+)/$', views.search_mdd),
    url(r'^(\d+)/(.+)$', views.search_mdd),
    url(r'^dic/(\d+)/$', views.mdict_dic),
    url(r'^dic/(\d+)/(.+)$', views.search_mdd),
    url(r'^es/(\d+)/(.+)$', views.search_mdd),
    url(r'^esdic/(\d+)/(.+)$', views.search_mdd),
    url(r'^shelf/(\d+)/(.+)$', views.search_mdd),
    url(r'^shelf2/(\d+)/(.+)$', views.search_mdd),
    path('exfile/', views.get_external_file),
    url('exfile/(.+)', views.get_external_file),
    path('es/exfile/', views.get_external_file),
    url('es/exfile/(.+)', views.get_external_file),
    path('audio/', views.search_audio),
    path('key/', views.search_mdx_key),
    path('record/', views.search_mdx_record),
    path('allentrys/', views.mdict_all_entrys),
    path('getlbocknum/', views.get_block_num),
    path('mdictlist/', views.get_mdict_list),
    path('header/', views.get_dic_info),
    path('dicgroup/', views.get_dic_group),
    path('mdictenable/', views.set_mdict_enable),
    path('retrieveconfig/', views.retrieve_config),
    path('saveconfig/', views.save_config),
    path('bujian/', views.bujianjiansuo),
    path('es/', views.es_index),
    path('essearch/', views.fulltext_search),
    path('initindex/', views.init_index),
    path('indexstatus/', views.get_index_status),
    path('downloadhistory/', views.download_history),
    path('wordcloud/', views.wordcloud),
    path('getwordlist/', views.getwordlist),
    url(r'^esdic/(\d+)/$', views.es_dic),
    url(r'^zim/(\d+)/(.+)$', views.search_zim),
    url(r'^dic/zim/(\d+)/(.+)$', views.search_zim),
    url(r'^es/zim/(\d+)/(.+)$', views.search_zim),
    url(r'^zim/$', views.search_zim_dic),
    path('randomsearch/', views.random_search),
    path('getpkingroup/', views.get_pk_in_group),
    path('shelf/', views.shelf),
    path('shelf2/', views.shelf2),
    path('doc/', views.doc),
    url('doc/(.+)', views.doc_md),
    path('addtogroup/', views.add_to_group),
    path('deleteitem/', views.delete_item),
    path('renameitem/', views.rename_item),
    path('moveitem/', views.move_item),
    path('grouping/', views.grouping),
    path('grouping/mdictpath/', views.grouping_mdictpath),
    path('grouping/mdictgroup/', views.grouping_mdictgroup),
    path('grouping/creategroup/', views.create_group),
]
